CloudP0Events/CloudP0Events/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('eventos/', include('eventos.urls')),
    path('admin/', admin.site.urls),
]

CloudP0Events/eventos/urls.py
from django.urls import path

from . import views

app_name = 'eventos'
urlpatterns = [
    path('', views.index, name='index'),
    path('lista_eventos/', views.lista_eventos_service, name='lista_eventos'),
    path('registro/', views.registro, name='registro'),
    path('adicionar_usuario/', views.adicionar_usuario, name='adicionar_usuario'),
    path('login/', views.login_service, name='login'),
    path('logout/', views.logout_service, name='logout'),
    path('evento/<int:evento_id>', views.detalle_evento, name='detalle_evento'),
    path('evento/<int:evento_id>/', views.detalle_evento, name='detalle_evento_con'),
    path('evento/<int:evento_id>/editar', views.editar_detalle_evento, name='editar_evento'),
    path('evento/<int:evento_id>/eliminar', views.eliminar_evento, name='eliminar_evento'),
    path('evento/crear_evento/', views.crear_evento_form, name='crear_evento'),
    path('evento/adicionar_evento/', views.adicionar_evento, name='adicionar_evento'),
]

CloudP0Events/eventos/models.py
from django.db import models
from django.contrib.auth.models import User
from django.forms import ModelForm
from django import forms

# Create your models here.



class UserForm(ModelForm):

    username = forms.EmailField()
    first_name = forms.CharField(max_length=20)
    last_name = forms.CharField(max_length=20)
    password = forms.CharField(widget=forms.PasswordInput())
    password2 = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'password', 'password2']


class Categoria(models.Model):
    nombre = models.CharField(max_length=50)
    fecha_creacion = models.DateField('fecha creacion')
    hora_creacion = models.TimeField('hora creacion')
    usuario_creacion = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.nombre


class Evento(models.Model):
    nombre = models.CharField(max_length=200)
    categoria = models.ForeignKey(Categoria, on_delete=models.CASCADE)
    lugar = models.CharField(max_length=100)
    direccion = models.CharField(max_length=200)
    fecha_inicio = models.DateField('fecha inicio')
    fecha_fin = models.DateField('fecha fin')
    es_presencial = models.BooleanField()
    fecha_creacion = models.DateField('fecha creacion')
    hora_creacion = models.TimeField('hora creacion')
    usuario_creacion = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.nombre


class EventoForm(ModelForm):
    class Meta:
        model = Evento
        fields = ['nombre', 'categoria', 'lugar', 'direccion', 'fecha_inicio', 'fecha_fin', 'es_presencial']

CloudP0Events/eventos/views.py
from __future__ import unicode_literals

from django.contrib import messages
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.models import User
from django.core import serializers
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_list_or_404
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt
from .models import Evento, UserForm, Categoria, EventoForm
from django.utils import timezone

# Create your views here.


def index(request):
    return render(request, "eventos/index.html")


def registro(request):
    if not request.user.is_authenticated:
        form = UserForm
        return render(request, 'eventos/registro.html', {'form': form})
    return HttpResponseRedirect(reverse('eventos:index'))

@csrf_exempt
def adicionar_usuario(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        password = request.POST.get('password')

        try:
            user_existe = User.objects.get(username=username)
        except:
            user_existe = None

        if user_existe is None:
            user_model = User.objects.create_user(username=username, password=password)
            user_model.first_name = first_name
            user_model.last_name = last_name
            user_model.save()
            messages.success(request, "Usuario creado con exito!", extra_tags='alert alert-success')
            ruta = 'eventos:index'

        else:
            messages.warning(request, "No se puede crear el usuario, porque ya existe.", extra_tags='alert alert-warning')
            ruta = 'eventos:registro'
    else:
        ruta = 'eventos:index'
    return HttpResponseRedirect(reverse(ruta))


@csrf_exempt
def login_service(request):
    if request.method == 'POST':
        if not request.user.is_authenticated:
            usuario = request.POST.get('usuario')
            contrasena = request.POST.get('contrasena')
            user = authenticate(username=usuario, password=contrasena)
            if user is not None:
                login(request, user)
            else:
                messages.error(request, "Usuario o contraeña inválidos.", extra_tags='alert alert-danger')

    return HttpResponseRedirect(reverse('eventos:index'))


def logout_service(request):
    logout(request)
    return HttpResponseRedirect(reverse('eventos:index'))


@csrf_exempt
def lista_eventos_service(request):
    if request.user.is_authenticated:
        usuario = User.objects.filter(username=request.user).first()
        lista = Evento.objects.filter(usuario_creacion=usuario).order_by('-fecha_creacion', '-hora_creacion')
        return HttpResponse(serializers.serialize("json", lista))
    return HttpResponseRedirect(reverse('eventos:index'))


def detalle_evento(request, evento_id):
    if request.user.is_authenticated:
        usuario_autenticado = User.objects.filter(username=request.user).first()
        if usuario_autenticado is not None:
            evento_seleccionado = Evento.objects.filter(id=evento_id, usuario_creacion=usuario_autenticado).first()
            if evento_seleccionado is not None:
                lista_categorias = get_list_or_404(Categoria)
                form = EventoForm
                form.nombre = evento_seleccionado.nombre

                context = {
                    'evento_seleccionado': evento_seleccionado,
                    'lista_categorias': lista_categorias,
                    'form': form,
                }
                return render(request, 'eventos/detalle.html', context)
            else:
                messages.warning(request, "No se tiene permiso para visualizar el evento seleccionado", extra_tags='alert alert-warning')
    return HttpResponseRedirect(reverse('eventos:index'))


def editar_detalle_evento(request, evento_id):
    if request.user.is_authenticated:
        usuario_autenticado = User.objects.filter(username=request.user).first()
        if usuario_autenticado is not None:
            evento_editar = Evento.objects.filter(id=evento_id, usuario_creacion=usuario_autenticado).first()
            if evento_editar is not None:
                try:
                    evento_editar.nombre = request.POST['nombre']
                    categoria_seleccionada = Categoria.objects.filter(id=request.POST['categoria']).first()
                    evento_editar.categoria = categoria_seleccionada
                    evento_editar.lugar = request.POST['lugar']
                    evento_editar.direccion = request.POST['direccion']
                    evento_editar.fecha_inicio = request.POST['finicio']
                    evento_editar.fecha_fin = request.POST['ffin']
                    evento_editar.es_presencial = True if request.POST.get('es_presencial', None) else False
                    if evento_editar.fecha_fin < evento_editar.fecha_inicio:
                        messages.error(request, "Error al editar evento, la fecha de fin debe ser mayor a la fecha de inicio!", extra_tags='alert alert-danger')
                    else:
                        evento_editar.save()
                        messages.success(request, "Evento editado con exito!", extra_tags='alert alert-success')
                except:
                    messages.error(request, "Error al editar el evento!", extra_tags='alert alert-danger')

            else:
                messages.error(request, "Error al editar el evento!", extra_tags='alert alert-danger')
    return HttpResponseRedirect(reverse('eventos:index'))


def crear_evento_form(request):
    form = EventoForm
    lista_categorias = get_list_or_404(Categoria)

    context = {
        'lista_categorias': lista_categorias,
        'form': form,
    }
    return render(request, 'eventos/crear_evento.html', context)


@csrf_exempt
def adicionar_evento(request):
    if request.user.is_authenticated:
        if request.method == 'POST':
            nombre = request.POST.get('nombre')
            categoria = Categoria.objects.filter(id=request.POST.get('categoria')).first()
            lugar = request.POST.get('lugar')
            direccion = request.POST.get('direccion')
            fecha_inicio = request.POST.get('fecha_inicio')
            fecha_fin = request.POST.get('fecha_fin')
            if request.POST.get('es_presencial') == 'on':
                bool_presencial = True
            else:
                bool_presencial = False

            usuario_creacion = User.objects.filter(username=request.user).first()
            if usuario_creacion is not None and categoria is not None:
                try:
                    evento_existe = Evento.objects.get(nombre=nombre, categoria=categoria, lugar=lugar,
                                                       direccion=direccion, fecha_inicio=fecha_inicio,
                                                       fecha_fin=fecha_fin, es_presencial=bool_presencial,
                                                       usuario_creacion=usuario_creacion)
                except:
                    evento_existe = None

                if evento_existe is None:
                    try:
                        evento_model = Evento(nombre=nombre, categoria=categoria, lugar=lugar, direccion=direccion,
                                              fecha_inicio=fecha_inicio, fecha_fin=fecha_fin,
                                              fecha_creacion=timezone.now().date(), hora_creacion=timezone.now().strftime("%H:%M:%S"),
                                              es_presencial=bool_presencial,
                                              usuario_creacion=usuario_creacion)
                        if fecha_fin < fecha_inicio:
                            ruta = 'eventos:crear_evento'
                            messages.error(request, "Error al crear evento, la fecha de fin debe ser mayor a la fecha de inicio!", extra_tags='alert alert-danger')
                        else:
                            evento_model.save()
                            messages.success(request, "Evento creado con exito!", extra_tags='alert alert-success')
                    except:
                        messages.error(request, "Error creando evento!", extra_tags='alert alert-danger')

                    ruta = 'eventos:index'

                else:
                    messages.warning(request, "No se puede crear el evento, porque ya existe.", extra_tags='alert alert-warning')
                    ruta = 'eventos:index'
            else:
                messages.warning(request, "No existe el usuario o la categoria", extra_tags='alert alert-warning')
                ruta = 'eventos:index'
    else:
        messages.warning(request, "No tiene permisos para crear el evento.", extra_tags='alert alert-warning')
        ruta = 'eventos:index'

    return HttpResponseRedirect(reverse(ruta))


def eliminar_evento(request, evento_id):
    if request.user.is_authenticated:
        usuario_autenticado = User.objects.filter(username=request.user).first()
        if usuario_autenticado is not None:
            evento_eliminar = Evento.objects.filter(id=evento_id, usuario_creacion=usuario_autenticado).first()

            if evento_eliminar is not None:
                try:
                    evento_eliminar.delete()
                    messages.success(request, "Evento eliminado con exito!", extra_tags='alert alert-success')
                except:
                    messages.error(request, "Error al eliminar el evento!", extra_tags='alert alert-danger')

            else:
                messages.error(request, "Error al eliminar el evento!", extra_tags='alert alert-danger')
    return HttpResponseRedirect(reverse('eventos:index'))

CloudP0Events/eventos/templates/eventos/crear_evento.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Crear Evento{% endblock %}
{% block script %}
       <script type="text/javascript" src="{% static 'eventos/js/crear_evento.js' %}"></script>
{% endblock script %}

{% block content %}

<div class="row">
    <div class="col-md-6 col-sm-offset-3">
        <div class="page-header">
            <h2>Crear Evento</h2>
        </div>

        <form id="formulario_crear_evento" class="form-group" method="post" action="{% url 'eventos:adicionar_evento' %}">
            {% csrf_token %}
            {{ form|crispy }}

            <input type="submit" value="Crear"class="btn btn-primary" id="btn_crear">
            <a href="{% url 'eventos:index' %}" class="btn btn-primary">Cancel</a>

        </form>

    </div>

</div>
{% endblock %}
{% block script2 %}
       <script type="text/javascript" src="{% static 'eventos/js/crear_evento_end.js' %}"></script>
{% endblock script2 %}

CloudP0Events/eventos/templates/eventos/detalle.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Detalle Evento{% endblock %}

<div class="col-lg-10">
{% block content %}

{% if evento_seleccionado %}

    <div class="row">
        <div class="col-md-6 col-sm-offset-3">
            <div class="page-header">
                <h3><b>Editar Evento</b></h3>
            </div>


            <form action="{% url 'eventos:editar_evento' evento_seleccionado.id %}" method="post">
                {% csrf_token %}
                <b>Nombre: </b><input class="form-control" type="text" name="nombre" value="{{ evento_seleccionado.nombre }}"><br>
                <b>Categoria: </b><select class="form-control" name="categoria">
                    {% if evento_seleccionado %}
                    {% for categoria in lista_categorias %}
                    <option value="{{ categoria.id }}" {% if evento_seleccionado.categoria == categoria %}selected{% endif %}> {{ categoria.nombre }}  </option>
                    {% endfor %}
                    {% endif %}
                </select><br>
                <b>Lugar: </b><input class="form-control" type="text" name="lugar" value="{{ evento_seleccionado.lugar }}"><br>
                <b>Direccion: </b><input class="form-control" type="text" name="direccion" value="{{ evento_seleccionado.direccion }}"><br>
                <b>Fecha Inicio: </b><input id="finicio", name="finicio" type="text" class="form-control" value="{{evento_seleccionado.fecha_inicio|date:'Y-m-d'}}"><br>
                <b>Fecha Fin: </b><input id="ffin", name="ffin" class="form-control" type="text" value="{{ evento_seleccionado.fecha_fin|date:'Y-m-d' }}"> <br>
                <b>Es Presencial: </b><input class="form-check-input" type="checkbox" name="es_presencial" {% if evento_seleccionado.es_presencial == True %} checked {% endif %}><br>

                <input class="btn btn-primary mb-2" type="submit" value="Editar">
                <a href="/eventos/">volver</a>
            </form>
        {% else %}
            <p>No existe el evento seleccionado.</p>
        {% endif %}

        {% endblock %}
        </div>

    </div>
</div>
{% block script2 %}
       <script type="text/javascript" src="{% static 'eventos/js/detalle_evento_end.js' %}"></script>
{% endblock script2 %}

CloudP0Events/eventos/templates/eventos/index.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Eventos{% endblock %}
{% block script %}
    <script type="text/javascript" src="{% static 'eventos/js/listar_eventos.js' %}"></script>
    <script type="text/javascript" src="{% static 'eventos/js/helpers.js' %}"></script>
{% endblock script %}


{% block content %}

{% if user.is_authenticated %}
    Hola {{ user.username }}! <a href="{% url 'eventos:logout' %}">Cerrar sesion</a>
    <div class="header row">
    <div class="col-lg-6">
        <h3><b>Listado de eventos</b></h3>
    </div>

    </div>
    <div class="col-lg-10">
        <div>
            <button class="btn btn-primary mb-2 float-right" onClick="goToUrl('eventos/evento/crear_evento/')">Crear Evento</button>
        </div>
        <table id="lista_eventos_table" class="table">

        </table>
    </div>


{% else %}
    <div class ='row'>
        <div class="col-md-4 col-md-offset-4">
            <div class="page header">
                <h2>Iniciar Sesión</h2>
            </div>
            <form id="login_form" class="form-group" method="post" action="{% url 'eventos:login' %}">
                {% csrf_token %}
                <div class="form-group">
                    <label class="control-label" form="usuario">Nombre de usuario</label>
                    <input type="text" id="usuario" name="usuario" class="form-control" value="{{ usuario }}" required>
                </div>

                <div class="form-group">
                    <label for="contrasena">Contraseña</label>
                    <input type="password" name="contrasena" id="contrasena" class="form-control" required>
                </div>
                <button type="submit" id="aceptar" class="btn btn-primary">Ingresar</button>
            </form>
            <a href="{% url 'eventos:registro' %}" >   Registro</a>
        </div>
    </div>
{% endif %}
{% endblock %}

CloudP0Events/eventos/templates/eventos/registro.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Registro{% endblock %}
{% block script %}
       <script type="text/javascript" src="{% static 'eventos/js/registro.js' %}"></script>
{% endblock script %}

{% block content %}

<div class="row">
    <div class="col-md-6 col-sm-offset-3">
        <div class="page-header">
            <h2>Registro</h2>
        </div>

        <form id="formulario_registro" class="form-group" method="post" action="{% url 'eventos:adicionar_usuario' %}">
            {% csrf_token %}
            {{ form|crispy }}

            <input type="submit" value="Registrar"class="btn btn-primary" id="btn_registro">
            <a href="{% url 'eventos:index' %}" class="btn btn-primary">Cancel</a>

        </form>

    </div>

</div>
{% endblock %}